version: "3"

services:
  backend:
    container_name: backend
    build: ./backend/
    command: nodemon -L
    ports:
      - "8080:8080"
    volumes:
      - "./backend/:/backend"
  console:
    container_name: console
    build: ./console/
    command: npm start
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment:
      - BACKEND=backend
    #volumes:
    #  - "/Dark_Chain:/console"
  portals:
    container_name: portals
    build: ./portals/
    command: npm start
    ports:
      - "81:3000"
    depends_on:
      - backend
    environment:
      - BACKEND=backend
