version: "3"

services:
  backend:
    container_name: backend
    build: ./backend/
    command: nodemon -L
    ports:
      - "8080:8080"
    volumes:
      - "./backend/:/backend/"
  console:
    container_name: console
    build: ./console/
    command: npm start
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment:
      - BACKEND=backend
    volumes:
      - "./console/:/console/"
      - "/console/node_modules"
  portals:
    container_name: portals
    build: ./portals/
    command: npm start
    ports:
      - "81:3000"
    depends_on:
      - backend
    environment:
      - BACKEND=backend
    volumes:
      - "./portals/:/portals/"
      - "/portals/node_modules"
