version: "2"

services:
  backend:
    container_name: backend
    image: schmidtp0740/moei_backend:0.6
    ports:
      - "8080:8000"
  console:
    container_name: console
    image: schmidtp0740/moei_console:0.1
    command: npm start
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment:
      - BACKEND=backend
  portals:
    container_name: portals
    image: schmidtp0740/moei_portals:0.1
    command: npm start
    ports:
      - "81:3000"
    depends_on:
      - backend
    environment:
      - BACKEND=backend
